name: CI

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: write

jobs:
  build-test:
    name: "Build and Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Install Go dependencies
        run: go get .

      - name: Build the application
        run: go build -buildvcs

      - name: Lint the code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Create a test results directory
        run: mkdir test-results

      - name: Run tests
        run: |
          go test "./..." -coverprofile="test-results/coverage.out" -covermode=count
          go test "./..." -coverprofile="coverage.out" -covermode=count -json > test-report.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
